<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	

	<!-- This part of the file looks like it is not necessary for the correct function of the urdf files.-->
	<!-- Remove this part in a second iteration when all functions are working like they are supposed to be-->
	<!-- <xacro:macro name="diff_controller_plugin_gazebo" params="prefix left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
		<gazebo>
			<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<legacyMode>false</legacyMode>
				<alwaysOn>true</alwaysOn>
				<updateRate>1000.0</updateRate>
				<leftJoint>${left_wheel_joint}</leftJoint>
				<rightJoint>${right_wheel_joint}</rightJoint>
				<wheelSeparation>${wheel_separation}</wheelSeparation>
				<wheelDiameter>${2*wheel_radius}</wheelDiameter>
				<wheelTorque>10</wheelTorque>
				<publishTf>1</publishTf>
				<odometryFrame>map</odometryFrame>
				<commandTopic>mobile_base_controller/cmd_vel</commandTopic>
				<odometryTopic>mobile_base_controller/odom</odometryTopic>
				<robotBaseFrame>base_footprint</robotBaseFrame>
				<wheelAcceleration>2.8</wheelAcceleration>
				<publishWheelJointState>true</publishWheelJointState>
				<publishWheelTF>false</publishWheelTF>
				<odometrySource>world</odometrySource>
				<rosDebugLevel>Debug</rosDebugLevel>
			</plugin>
		</gazebo>
	</xacro:macro> -->
</robot>
