<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find mir_description)/urdf/general/imu.gazebo.xacro" />

	<xacro:property name="imu_standard_deviation" value="0.00017" />

	<xacro:macro name="mir_100_gazebo" params="tf_prefix">

		<!-- Set Gazebo material for the base -->
		<gazebo reference="${prefix}base_link">
			<material>Gazebo/White</material>
		</gazebo>

		<!-- Settings for the IMU of the robot to work in the simulation environment-->
		<xacro:imu_gazebo link="${tf_prefix}imu_link" imu_topic="imu_data" update_rate="50.0" standard_deviation="${imu_standard_deviation}" />

		<p3d_base_controller prefix="${prefix}" />

		<!-- wheels -->
		<xacro:actuated_wheel_gazebo tf_prefix="${tf_prefix}" locationprefix="left"/>
		<xacro:actuated_wheel_gazebo tf_prefix="${tf_prefix}" locationprefix="right"/>
		<xacro:caster_wheel_gazebo tf_prefix="${tf_prefix}" locationprefix="fl"/>
		<xacro:caster_wheel_gazebo tf_prefix="${tf_prefix}" locationprefix="fr"/>
		<xacro:caster_wheel_gazebo tf_prefix="${tf_prefix}" locationprefix="bl"/>
		<xacro:caster_wheel_gazebo tf_prefix="${tf_prefix}" locationprefix="br"/>

		<!-- This part of the file looks like it is not necessary for the correct function of the urdf files.-->
		<!-- Remove this part in a second iteration when all functions are working like they are supposed to be-->

		<!-- disabled, because it doesn't make a difference in Gazebo: -->
		<!-- <xacro:set_all_wheel_frictions prefix="${prefix}"/> -->

		<!-- <xacro:macro name="diff_controller_plugin_gazebo" params="prefix left_wheel_joint right_wheel_joint wheel_separation wheel_radius">
			<gazebo>
				<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
					<legacyMode>false</legacyMode>
					<alwaysOn>true</alwaysOn>
					<updateRate>1000.0</updateRate>
					<leftJoint>${left_wheel_joint}</leftJoint>
					<rightJoint>${right_wheel_joint}</rightJoint>
					<wheelSeparation>${wheel_separation}</wheelSeparation>
					<wheelDiameter>${2*wheel_radius}</wheelDiameter>
					<wheelTorque>10</wheelTorque>
					<publishTf>1</publishTf>
					<odometryFrame>map</odometryFrame>
					<commandTopic>mobile_base_controller/cmd_vel</commandTopic>
					<odometryTopic>mobile_base_controller/odom</odometryTopic>
					<robotBaseFrame>base_footprint</robotBaseFrame>
					<wheelAcceleration>2.8</wheelAcceleration>
					<publishWheelJointState>true</publishWheelJointState>
					<publishWheelTF>false</publishWheelTF>
					<odometrySource>world</odometrySource>
					<rosDebugLevel>Debug</rosDebugLevel>
				</plugin>
			</gazebo>
		</xacro:macro> -->
</robot>
