joint_names:
  - elbow_joint
  - shoulder_lift_joint
  - shoulder_pan_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
file_name: $(find mur_hardware_helper)/poses/transport_poses.yaml
max_joint_velocity: 0.5 