theme: jekyll-theme-slate
title: Mobile robotics at the Institute for Assembly Technology
description: This websides contains useful documentation, sources and explanations for working with mobile robots.
